// DOM Elements
const elHTML = document.getElementById('html-code');
const elCSS = document.getElementById('css-code');
const elJS = document.getElementById('js-code');
const toast = document.getElementById('toast');
const toastMsg = document.getElementById('toast-message');
const toastIco = document.getElementById('toast-icon');

let toastTimeout;

// --- UI Utilities ---

/** 
 * Displays a temporary popup toast notification 
 */
function showToast(message, type = 'success') {
    toastMsg.textContent = message;

    // Reconfigure colors based on type
    toast.className = 'fixed bottom-6 right-6 bg-gray-800 border-l-4 text-gray-100 px-5 py-4 rounded-md shadow-2xl transition-all duration-300 z-50 flex items-center gap-3 flex flex-row translate-y-24 opacity-0';

    if (type === 'success') {
        toast.classList.add('border-brand-500');
        toastIco.className.baseVal = 'w-5 h-5 text-brand-500 shrink-0';
        toastIco.innerHTML = '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>';
    } else {
        toast.classList.add('border-red-500');
        toastIco.className.baseVal = 'w-5 h-5 text-red-500 shrink-0';
        toastIco.innerHTML = '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>';
    }

    // Trigger enter animation (use requestAnimationFrame to wait for styles to apply before transition)
    requestAnimationFrame(() => {
        toast.classList.remove('translate-y-24', 'opacity-0');
        toast.classList.add('translate-y-0', 'opacity-100');
    });

    // Auto-hide after 3 seconds
    clearTimeout(toastTimeout);
    toastTimeout = setTimeout(() => {
        toast.classList.remove('translate-y-0', 'opacity-100');
        toast.classList.add('translate-y-24', 'opacity-0');
    }, 3000);
}

// --- Core Functions ---

/** Get current code from all fields */
function getCode() {
    return {
        html: elHTML.value,
        css: elCSS.value,
        js: elJS.value
    };
}

/** Set code in fields */
function setCode(html, css, js) {
    elHTML.value = html || '';
    elCSS.value = css || '';
    elJS.value = js || '';
}

/** Clear inputs */
function clearAll() {
    if (elHTML.value === '' && elCSS.value === '' && elJS.value === '') return;
    if (confirm("Are you sure you want to clear all your code? This cannot be undone.")) {
        setCode('', '', '');
        window.history.replaceState(null, '', window.location.pathname); // clear URL hash
        showToast("All text areas cleared");
    }
}

/** 
 * LAUNCH PREVIEW: Safely execute code logic using the EXACT same page to maintain domain URL statically.
 */
function launchPreview() {
    const { html, css, js } = getCode();

    const hashParams = new URLSearchParams();
    hashParams.set('mode', 'preview'); // Tell the application to act as the previewer!
    if (html) hashParams.set('h', encodeCode(html));
    if (css) hashParams.set('c', encodeCode(css));
    if (js) hashParams.set('j', encodeCode(js));

    // Open the exact same URL without query strings but with the new hash
    const currentUrl = window.location.href.split('#')[0].split('?')[0];
    const previewUrl = `${currentUrl}#${hashParams.toString()}`;

    // Natively open up the exact URL!
    const newTab = window.open(previewUrl, '_blank');
    if (!newTab) {
        showToast("Your browser blocked the pop-up. Allow pop-ups to open the preview.", "error");
    }
}

/** 
 * SAVE ZIP: Zips the project natively in the browser leveraging JSZip 
 */
async function saveZip() {
    try {
        if (typeof JSZip === 'undefined') {
            showToast("JSZip library has not finished loading. Try again in a second.", "error");
            return;
        }

        const { html, css, js } = getCode();
        const zip = new JSZip();

        // Generate standard filesystem structure
        const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Web Project generated by CosmoTools</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
${html}
<script src="script.js"><\/script>
</body>
</html>`;

        zip.file("index.html", fullHtml);
        zip.file("style.css", css);
        zip.file("script.js", js);

        // Add required metadata and branding files
        zip.file("README.md", `# My Web Project\n\nGenerated efficiently using **Viewer by CosmoTools**.\n\nHappy Coding!`);
        zip.file("cosmotools-info.txt", `Project: CosmoTools\nRepository: https://github.com/bhuvanesh-m-dev/cosmotools\n\nViewer by CosmoTools is an ultra-fast, completely stateless, client-side previewer designed for straightforward frontend rapid prototyping.`);

        // Async generation and trigged download via blob
        const content = await zip.generateAsync({ type: "blob" });
        const blobUrl = URL.createObjectURL(content);

        const dummyLink = document.createElement("a");
        dummyLink.href = blobUrl;
        dummyLink.download = "my-web-project.zip";

        document.body.appendChild(dummyLink);
        dummyLink.click();
        document.body.removeChild(dummyLink);

        // Clean up references
        URL.revokeObjectURL(blobUrl);
        showToast("ZIP exported and downloading!");

    } catch (error) {
        console.error("ZIP Generation Error:", error);
        showToast("Failed to generate the ZIP package.", "error");
    }
}

// --- URL State Management (SHARE) ---

/** 
 * URL-safe base64 encoding 
 */
function encodeCode(str) {
    return btoa(encodeURIComponent(str || ''))
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
}

/** 
 * URL-safe base64 decoding 
 */
function decodeCode(b64) {
    if (!b64) return '';
    b64 = b64.replace(/-/g, '+').replace(/_/g, '/');
    while (b64.length % 4) b64 += '=';
    try {
        return decodeURIComponent(atob(b64));
    } catch (e) {
        console.warn('Failed decoding share parameter');
        return '';
    }
}

/** 
 * Generates current state as a shareable link copied to clipboard 
 */
function shareLink() {
    const { html, css, js } = getCode();

    // Using hash maps vs query parameters to easily evade server restrictions 
    // since this is a pure-client experience
    const hashParams = new URLSearchParams();
    if (html) hashParams.set('h', encodeCode(html));
    if (css) hashParams.set('c', encodeCode(css));
    if (js) hashParams.set('j', encodeCode(js));

    // Generate full URL
    const paramsString = hashParams.toString();
    // Optional: Handle case of empty codebase
    const shareUrl = paramsString.length > 0
        ? `${window.location.origin}${window.location.pathname}#${paramsString}`
        : `${window.location.origin}${window.location.pathname}`;

    navigator.clipboard.writeText(shareUrl).then(() => {
        showToast("Shareable link successfully copied to your clipboard!");
        // Modify browser URL silently to keep active context
        window.history.replaceState(null, '', shareUrl);
    }).catch(err => {
        console.error('Clipboard Context Error:', err);
        showToast("Failed to copy link automatically.", "error");
    });
}

/** 
 * Extracts param payload upon window start 
 */
function initializeFromState() {
    try {
        // Determine parameter sources (hash preference)
        let paramsText = '';
        if (window.location.hash) {
            paramsText = window.location.hash.substring(1);
        } else if (window.location.search) {
            paramsText = window.location.search.substring(1);
        }

        if (paramsText) {
            const params = new URLSearchParams(paramsText);
            const mode = params.get('mode');
            const h = decodeCode(params.get('h'));
            const c = decodeCode(params.get('c'));
            const j = decodeCode(params.get('j'));

            // If we are in Preview Mode, immediately overwrite the system UI
            // and build the user document natively!
            if (mode === 'preview') {
                const previewDoc = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Preview Result</title>
    <style>${c}</style>
</head>
<body>
    ${h}
    <script>${j}<\/script>
</body>
</html>`;
                document.open();
                document.write(previewDoc);
                document.close();
                return; // Stop initialization of editor logic
            }

            // Otherwise, we are in Editor Mode, so load the code
            if (h || c || j) {
                setCode(h, c, j);
            }
        }
    } catch (error) {
        console.error("Link Serialization Error:", error);
    }
}

// --- Custom Behaviours ---

/** 
 * Enable soft Tabs behaviour in plain text areas 
 */
[elHTML, elCSS, elJS].forEach(textarea => {
    textarea.addEventListener('keydown', function (event) {
        if (event.key === 'Tab') {
            event.preventDefault();
            const start = this.selectionStart;
            const end = this.selectionEnd;

            // Insert 2 standard spaces (or 4 if preferred)
            const tabSpace = "  ";

            this.value = this.value.substring(0, start) + tabSpace + this.value.substring(end);
            this.selectionStart = this.selectionEnd = start + tabSpace.length;
        }
    });
});

// Initialize parameters logic
window.addEventListener('DOMContentLoaded', initializeFromState);
